import fs from 'fs-extra';
// @ts-ignore
import { format as prettify } from 'prettier';
import { Format } from '../index';
import { join } from 'path';

const prettierDefault = {
    semi: true,
    trailingComma: 'all',
    singleQuote: true,
    printWidth: 120,
    tabWidth: 4,
};

function getPrettierConfig(file?: string) {
    let config: any;
    if (file?.endsWith('.js')) {
        config = require(file);
    }
    if (file?.endsWith('.json') || file?.endsWith('rc')) {
        config = fs.readJSONSync(file);
    }

    if (config) {
        console.log('Using custom prettier config from file ', file);
        return config;
    }
    console.log('Using default prettier config');
    return prettierDefault;
}

export async function writeFormattedFile(args: {
    filename: string;
    directory: string;
    content: string;
    format: Format;
    prettierConfig?: string;
}) {
    const { filename, directory, content, format, prettierConfig } = args;

    let fileHeader = `
         /* Auto generated by relational-schema (https://github.com/MattGson/relational-schema) --- DO NOT MODIFY */
        
        /* eslint-disable */
    `;

    if (format === Format.json) fileHeader = '';

    const extension =
        format === Format.es6 ? 'js' : format === Format.commonJS ? 'js' : format === Format.typescript ? 'ts' : 'json';

    const parser = format === Format.typescript ? 'typescript' : format === Format.json ? 'json' : undefined;

    const out = join(directory, filename + '.' + extension);

    // append creates files if they don't exist - write overwrites contents
    await fs.appendFile(out, '');
    await fs.writeFile(out, prettify(fileHeader + content, { parser, ...getPrettierConfig(prettierConfig) }));
}
