import fs from 'fs-extra';
// @ts-ignore
import { format as prettify } from 'prettier';
import { join } from 'path';
import { Format } from '../types';

const prettierDefault = {
    semi: true,
    trailingComma: 'all',
    singleQuote: true,
    printWidth: 120,
    tabWidth: 4,
};

const formatExtension = {
    [Format.json]: 'json',
    [Format.es6]: 'js',
    [Format.commonJS]: 'js',
    [Format.typescript]: 'ts',
};

const formatParser = {
    [Format.json]: 'json',
    [Format.es6]: 'babel',
    [Format.commonJS]: 'babel',
    [Format.typescript]: 'typescript',
};

function getPrettierConfig(file?: string) {
    let config: any;
    if (file?.endsWith('.js')) {
        config = require(file);
    }
    if (file?.endsWith('.json') || file?.endsWith('rc')) {
        config = fs.readJSONSync(file);
    }

    if (config) {
        console.log('Using custom prettier config from file ', file);
        return config;
    }
    console.log('Using default prettier config');
    return prettierDefault;
}

export async function writeFormattedFile(args: {
    filename: string;
    directory: string;
    content: string;
    format: Format;
    prettierConfig?: string;
}): Promise<void> {
    const { filename, directory, content, format, prettierConfig } = args;

    let fileHeader = `
         /* Auto generated by relational-schema (https://github.com/MattGson/relational-schema) --- DO NOT MODIFY */
        
        /* eslint-disable */
    `;

    if (format === Format.json) fileHeader = '';
    const extension = formatExtension[format];
    const parser = formatParser[format];

    const out = join(directory, filename + '.' + extension);

    // append creates files if they don't exist - write overwrites contents
    await fs.appendFile(out, '');
    await fs.writeFile(out, prettify(fileHeader + content, { parser, ...getPrettierConfig(prettierConfig) }));
}
