name: draft-release
on:
  push:
    branches:
      - main
      - master
    # Sequence of patterns matched against refs/tags
    tags:
      - v**

jobs:
  create-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path:
          draft: false
          prerelease: false
