name: version
on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
      - master

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

#    steps:
#      - name: 'Automated Version Bump'
#        uses: 'phips28/gh-action-bump-version@master'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PACKAGEJSON_DIR: './'
#        with:
#          tag-prefix: 'v'
#          # make sure version commit doesn't trigger loop
#          commit-message: 'CI: bumps version to {{version}} [skip ci]'